image: 'maven:3-jdk-8'
stages:
    - test
    - build
services:
  - 'mysql:5.5'
variables:
 MYSQL_DATABASE: citydb
 MYSQL_CI_URL: jdbc:mysql://localhost/citydb
 MYSQL_USER: test
 MYSQL_PASSWORD: test123
 MYSQL_ROOT_PASSWORD: root
cache:
  paths:
  - .m2/repository
  - target
maven-test:
 stage: test
 script: "mvn test -B"
maven-build:
 stage: build
 script: "mvn package -U"
 artifacts:
  paths:
  - target/*.jar